services:
    tymex-interview-frontend-dongduong:
        container_name: tymex-interview-frontend-dongduong
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        env_file:
            - .env
